spring:
  profiles:
    active: 
  datasource: 
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: 
mybatis:
   typeAliasesPackage: com.example.Eureka.*.entity
   mapperLocations: classpath*:mapping/*.xml
